name 'lamp'
maintainer 'Nathan Winther'
maintainer_email 'hello@nathanwinther.info'
license 'all_rights'
description 'Installs/Configures lamp'
long_description 'Installs/Configures lamp'
version '0.1.2'

depends 'apt', '~> 3.0.0'
depends 'firewall', '~> 2.5.0'
depends 'httpd', '~> 0.3.5'
depends 'mysql2_chef_gem', '~> 1.0.2'
depends 'mysql', '~> 6.1.3'
depends 'database', '~> 5.0.0'

